
services:
    - docker:dind

stages:
    - build
    # - test
    - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

image: docker:latest

build:
    stage: build
    script:
        # собственно сборка
        - docker-compose build
        # отправка собранного в registry
        - docker-compose push

# test:
#     stage: test
#     script:
#         # вместо повторной сборки, забираем собранный на предыдущей ступени
#         #  готовый образ из registry
#         - docker-compose pull test
#         # запускаем тесты
#         - docker-compose run test

k8s_deploy_back:
  stage: deploy
  image:  hub.66bit.ru/shared/stk8s:1.26.2
  script:
    - kubectl delete -f cube-deployment.yaml
    - kubectl apply -f cube-deployment.yaml
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
