  stages:
    - build
    - deploy

  variables:
    TAG_LATEST: $CI_REGISTRY_IMAGE:latest

  image: docker:latest

  build:
    stage: build
    before_script:
      - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
      - docker build --pull -t $TAG_LATEST -f Dockerfile .
      - docker push $TAG_LATEST
    after_script:
      - docker logout $CI_REGISTRY
    when: manual
    only:
      - main

  k8s_deploy_back:
    stage: deploy
    image:  hub.66bit.ru/shared/stk8s:1.26.2
    script:
      - kubectl delete -f cube-deployment.yaml
      - kubectl apply -f cube-deployment.yaml
    rules:
      - if: $CI_COMMIT_BRANCH == "main"
        when: manual
