version: '2'
services:
    web:
        build: ./web
        hostname: budgetsmart.stk8s.66bit.ru/
        environment:
            - SECRET_KEY
        command: uwsgi /usr/src/app/uwsgi.ini
        volumes:
            - static:/srv/static
        restart: unless-stopped

    # test:
    #     image: registry.gitlab.com/username/project:${CI_BUILD_REF_NAME}
    #     command: python manage.py test
    #     restart: "no"

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=root
            - POSTGRES_DB=database
        volumes:
            - data:/var/lib/postgresql/data
        restart: unless-stopped

    nginx:
        image: nginx:mainline
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx:/etc/nginx:ro
            - static:/srv/static:ro
        depends_on:
            - web
        restart: unless-stopped
