# Generated by Django 3.2.18 on 2023-05-14 08:15

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230514_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[users.validators.positive_number_validator]),
        ),
    ]
