# Generated by Django 3.2.18 on 2023-05-14 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[users.validators.positive_number_validator]),
        ),
        migrations.CreateModel(
            name='RegularTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[users.validators.positive_number_validator])),
                ('date', models.DateField()),
                ('periodicity', models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default='Day', max_length=10)),
                ('time_of_notification', models.TimeField()),
                ('comment', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.categorymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
