# Generated by Django 3.2.18 on 2023-05-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230514_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulartransaction',
            name='periodicity',
            field=models.CharField(choices=[('День', 'День'), ('Неделя', 'Неделя'), ('Месяц', 'Месяц'), ('Год', 'Год')], default='День', max_length=10),
        ),
    ]
