# Generated by Django 3.2.19 on 2023-05-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_regulartransaction_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='key',
            field=models.CharField(blank=True, choices=[('Расходы', 'Расходы'), ('Доходы', 'Доходы')], default='Расходы', max_length=100),
        ),
        migrations.AddField(
            model_name='regulartransaction',
            name='key',
            field=models.CharField(blank=True, choices=[('Расходы', 'Расходы'), ('Доходы', 'Доходы')], default='Расходы', max_length=100),
        ),
    ]
